"""
Manifest — centralized result registry.

Every paper-bound value is recorded to a JSON manifest and a LaTeX macro file.
No hand-transcribed numbers in the manuscript.
"""

import json
import os
import subprocess
from datetime import datetime
from pathlib import Path


class Manifest:
    """Result registry for the (rho, Pi) pipeline."""
    
    def __init__(self, results_dir: str):
        self.results_dir = Path(results_dir)
        self.results_dir.mkdir(parents=True, exist_ok=True)
        self.data = {
            "meta": self._get_meta(),
            "entries": {},
            "thresholds": {}
        }
    
    def _get_meta(self):
        """Capture version info."""
        meta = {
            "timestamp": datetime.utcnow().isoformat(),
            "pipeline_version": "1.0.0",
        }
        try:
            result = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                capture_output=True, text=True, timeout=5,
                cwd=Path(__file__).resolve().parent.parent
            )
            meta["git_commit"] = result.stdout.strip()
        except Exception:
            meta["git_commit"] = "unknown"
        
        # Record numpy version for reproducibility
        import numpy
        import scipy
        meta["numpy_version"] = numpy.__version__
        meta["scipy_version"] = scipy.__version__
        
        return meta
    
    def record(self, key: str, value, ci=None, units="", section="", table="",
               description="", threshold=None):
        """Register a paper-bound value."""
        entry = {
            "value": value,
            "units": units,
            "section": section,
            "table": table,
            "description": description,
            "threshold": threshold,
        }
        if ci is not None:
            entry["ci_lo"] = ci[0]
            entry["ci_hi"] = ci[1]
        self.data["entries"][key] = entry
    
    def register_threshold(self, key: str, value, description=""):
        """Register a pre-registered falsification threshold."""
        self.data["thresholds"][key] = {
            "value": value,
            "description": description
        }
    
    def save_json(self, filename="manifest.json"):
        """Save full manifest as JSON."""
        path = self.results_dir / filename
        with open(path, "w") as f:
            json.dump(self.data, f, indent=2, default=str)
        return str(path)
    
    def save_latex(self, filename="manifest.tex"):
        """Generate LaTeX \\newcommand macros for all entries.
        
        Every value becomes a \\newcommand{\\manifest{key}}{value} macro.
        For CI values, also emit \\manifest{key_lo} and \\manifest{key_hi}.
        """
        lines = [
            "% Auto-generated by the (rho, Pi) pipeline.",
            f"% Generated: {self.data['meta']['timestamp']}",
            f"% Git commit: {self.data['meta'].get('git_commit', 'unknown')}",
            "%",
            "% Each macro is used in the LaTeX manuscript as \\manifest{key}",
            "% to avoid hand-transcribed numbers.",
            "%",
        ]
        
        for key, entry in self.data["entries"].items():
            val = entry["value"]
            # Format numeric values sensibly
            if isinstance(val, float):
                if abs(val) < 0.01 or abs(val) > 1000:
                    fmt_val = f"{val:.6e}"
                elif abs(val) < 1:
                    fmt_val = f"{val:.6f}"
                else:
                    fmt_val = f"{val:.4f}"
            else:
                fmt_val = str(val)
            
            # Escape underscores in key for LaTeX
            safe_key = key.replace("_", "\\_")
            lines.append(f"\\newcommand{{\\manifest{{{safe_key}}}}}{{{fmt_val}}}")
            
            # CI values
            if "ci_lo" in entry and "ci_hi" in entry:
                lo = entry["ci_lo"]
                hi = entry["ci_hi"]
                if isinstance(lo, float):
                    fmt_lo = f"{lo:.4f}" if abs(lo) >= 0.01 else f"{lo:.6f}"
                    fmt_hi = f"{hi:.4f}" if abs(hi) >= 0.01 else f"{hi:.6f}"
                else:
                    fmt_lo = str(lo)
                    fmt_hi = str(hi)
                lines.append(f"\\newcommand{{\\manifest{{{safe_key}\\_{lo}}}}}{{{fmt_lo}}}")
                lines.append(f"\\newcommand{{\\manifest{{{safe_key}\\_{hi}}}}}{{{fmt_hi}}}")
        
        # Also emit thresholds
        for key, thr in self.data["thresholds"].items():
            safe_key = key.replace("_", "\\_")
            lines.append(f"% Threshold: {safe_key} = {thr['value']} ({thr['description']})")
        
        path = self.results_dir / filename
        with open(path, "w") as f:
            f.write("\n".join(lines) + "\n")
        return str(path)