#!/usr/bin/env python3
"""
run_pipeline.py — Consolidated pipeline for the (ρ, Π) Bridge Revision.
Runs all available analyses, merges all manifest records, generates figures,
and writes a single unified manifest.tex + manifest.json.
"""

import sys, os, json, subprocess, time

BASE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(BASE, "results")
os.makedirs(RESULTS, exist_ok=True)

def run_script(name):
    path = os.path.join(BASE, "analyses", name)
    print(f"\n{'='*60}")
    print(f"Running: {name}")
    print(f"{'='*60}")
    result = subprocess.run(
        [sys.executable, path],
        capture_output=True, text=True, timeout=600,
        cwd=BASE,
        env={**os.environ, "PYTHONPATH": f"{BASE}:{os.environ.get('PYTHONPATH', '')}"}
    )
    print(result.stdout[-1500:] if result.stdout else "")
    if result.returncode != 0:
        print(f"ERROR (exit {result.returncode}):")
        print(result.stderr[-2000:] if len(result.stderr) > 2000 else result.stderr)
    return result.returncode == 0


def merge_manifests():
    """Merge all manifest.json records into a single file."""
    manifest_path = os.path.join(RESULTS, "manifest.json")
    if not os.path.exists(manifest_path):
        print("No manifest to merge.")
        return None
    
    with open(manifest_path) as f:
        doc = json.load(f)
    
    records = doc.get("results", [])
    print(f"\nManifest has {len(records)} records total.")
    
    # Write unified manifest.tex
    lines = [
        "% Auto-generated by manifest.py — unified pipeline",
        f"% {time.strftime('%Y-%m-%dT%H:%M:%S+00:00', time.gmtime())}",
        "%",
        "% Pipeline results: all numbers referenced by main_v3.tex",
        "%",
    ]
    
    for rec in records:
        key = rec["key"].replace(".", "_")
        val = rec["value"]
        if val is None:
            continue  # skip placeholders
        if isinstance(val, float):
            if abs(val) < 1e-3 or abs(val) > 1e4:
                tex_val = f"{val:.4e}"
            else:
                tex_val = f"{val:.4f}"
            if rec.get("ci") and rec["ci"][0] is not None:
                lo, hi = rec["ci"]
                tex_val = f"{tex_val}^{{+{hi:.4f}}}_{{-{lo:.4f}}}"
        elif isinstance(val, str):
            tex_val = val.replace("_", "\\_")
        else:
            tex_val = str(val)
        macro = f"\\newcommand{{\\{key}}}{{{tex_val}}}"
        lines.append(macro)
    
    tex_path = os.path.join(RESULTS, "manifest.tex")
    with open(tex_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {tex_path} ({len(records)} macros)")


def pipeline_summary():
    """Print a quick summary of what the pipeline found."""
    manifest_path = os.path.join(RESULTS, "manifest.json")
    if not os.path.exists(manifest_path):
        return
    with open(manifest_path) as f:
        doc = json.load(f)
    recs = doc.get("results", [])
    print(f"\n{'='*60}")
    print("PIPELINE SUMMARY — KEY FINDINGS")
    print(f"{'='*60}")
    
    # Group by section
    for rec in recs:
        key = rec["key"]
        val = rec["value"]
        if val is None:
            continue
        if isinstance(val, float) and abs(val) < 1e-10:
            continue
        print(f"  {key:35s} = {val}")


if __name__ == "__main__":
    t0 = time.time()
    
    # Phase 1: T6 — Fisher sweep
    t6_ok = run_script("t06_fisher_sweep.py")
    
    # Phase 2: T5/T7/T8/T9 — Downstream analyses
    t5_ok = run_script("t05_t07_t08_t09.py")
    
    # Generate figures
    fig_ok = run_script(os.path.join("..", "generate_figures.py"))
    
    # Merge manifests
    merge_manifests()
    
    # Summary
    t1 = time.time()
    print(f"\n{'='*60}")
    print(f"Pipeline finished in {t1-t0:.1f}s")
    print(f"  T6 (Fisher sweep):    {'OK' if t6_ok else 'FAILED'}")
    print(f"  T5/T7/T8/T9:          {'OK' if t5_ok else 'FAILED'}")
    print(f"  Figures:              {'OK' if fig_ok else 'FAILED'}")
    
    pipeline_summary()