"""Constants for the organ measurement system, per REAL_ORGAN_DESIGN.md v0.2."""
from __future__ import annotations

HEARTBEAT_HZ = 10.0
HEARTBEAT_PERIOD_S = 1.0 / HEARTBEAT_HZ

RING_BUFFER_SIZE = 1000

CONTINUOUS_EVERY = 10
BURST_DURATION_BEATS = 100

WINDOW_SIZE = 500
UPDATE_FREQUENCY = 10
N_PERMUTATIONS = 1000
SIGNIFICANCE_THRESHOLD = 0.01
NORMALITY_P_THRESHOLD = 0.01
CONSTANT_DIM_THRESHOLD = 1e-15

LATENT_DRIVE_DIM = 3
DEFAULT_COUPLING = 0.6
NOISE_SCALE = 0.05
